import "./globals.css";
import {Providers} from "./providers";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
    <body>
    <SpeedInsights/>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  );
}
